// <auto-generated />
using System;
using Cuscuzeria.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cuscuzeria.Infra.Data.Migrations
{
    [DbContext(typeof(CuscuzeriaContext))]
    [Migration("20190310153433_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Cuscuzeria.Domain.Drink", b =>
                {
                    b.Property<int>("DrinkId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("DrinkName");

                    b.HasKey("DrinkId");

                    b.ToTable("Drinks");
                });

            modelBuilder.Entity("Cuscuzeria.Domain.Entities.Accompaniment", b =>
                {
                    b.Property<int>("AccompanimentId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccompanimentName");

                    b.Property<string>("Description");

                    b.HasKey("AccompanimentId");

                    b.ToTable("Accompaniments");
                });

            modelBuilder.Entity("Cuscuzeria.Domain.Entities.Beverage", b =>
                {
                    b.Property<int>("BeverageId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BeverageName");

                    b.Property<string>("Description");

                    b.HasKey("BeverageId");

                    b.ToTable("Beverages");
                });

            modelBuilder.Entity("Cuscuzeria.Domain.Entities.Cuscuz", b =>
                {
                    b.Property<int>("CuscuzId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccompanimentId");

                    b.Property<string>("CuscuzName");

                    b.Property<string>("Description");

                    b.Property<int>("TypeId");

                    b.HasKey("CuscuzId");

                    b.ToTable("Cuscuz");
                });

            modelBuilder.Entity("Cuscuzeria.Domain.Entities.Cuscuzeiro", b =>
                {
                    b.Property<int>("CuscuzeiroId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("CuscuzeiroName");

                    b.Property<DateTime>("StartDate");

                    b.Property<string>("UrlImg");

                    b.HasKey("CuscuzeiroId");

                    b.ToTable("Cuscuzeiros");
                });

            modelBuilder.Entity("Cuscuzeria.Domain.Entities.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BeverageId");

                    b.Property<int>("CuscuzId");

                    b.Property<int>("CuscuzeiroId");

                    b.Property<bool>("Delivered");

                    b.Property<int>("DrinkId");

                    b.Property<DateTime>("OrderCreation");

                    b.Property<int>("OrderStatus");

                    b.Property<int>("PromoId");

                    b.Property<int>("UserId");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Cuscuzeria.Domain.Entities.Promo", b =>
                {
                    b.Property<int>("PromoId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("Description");

                    b.Property<DateTime>("EndsAt");

                    b.Property<string>("PromoTitle");

                    b.Property<DateTime>("StartsAt");

                    b.HasKey("PromoId");

                    b.ToTable("Promos");
                });

            modelBuilder.Entity("Cuscuzeria.Domain.Entities.Type", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("TypeName");

                    b.HasKey("TypeId");

                    b.ToTable("Types");
                });

            modelBuilder.Entity("Cuscuzeria.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email");

                    b.Property<DateTime>("LastOrder");

                    b.Property<string>("Password");

                    b.Property<string>("UrlImg");

                    b.Property<string>("Username");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
